CREATE DATABASE IF NOT EXISTS appDB;
CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED BY 'password';
GRANT SELECT,UPDATE,INSERT ON appDB.* TO 'user'@'%';
FLUSH PRIVILEGES;

USE appDB;
CREATE TABLE IF NOT EXISTS users (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  login VARCHAR(20) NOT NULL,
  password VARCHAR(40) NOT NULL,
  PRIMARY KEY (ID)
);
CREATE TABLE IF NOT EXISTS parts (
  ID INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(20) NOT NULL,
  price INTEGER,
  PRIMARY KEY (ID)
);



INSERT INTO users (login, password)
SELECT * FROM (SELECT 'vbg', '{SHA}QL0AFWMIX8NRZTKeof9cXsvbvu8=') AS tmp
WHERE NOT EXISTS (
    SELECT login FROM users WHERE login='vbg' AND password='123'
) LIMIT 1;

INSERT INTO parts (name, price)
SELECT * FROM (SELECT 'koleso', 3000) AS tmp
WHERE NOT EXISTS (
    SELECT name FROM parts WHERE name = 'колесо' AND price = 3000
) LIMIT 1;

INSERT INTO parts (name, price)
SELECT * FROM (SELECT 'kapot', 1500) AS tmp
WHERE NOT EXISTS (
    SELECT name FROM parts WHERE name = 'капот' AND price = 5000
) LIMIT 1;

